### ISSUE TITLE
Add support for IDictionary<string, object> to Adapt

### ISSUE THREAD

**Issue by Jetski5822** [aspnet/EventNotification#14]
At the moment you can only pass in an anon type to the notifier in-order for parameter resolution to work, however, you don't always have an anon type. So it would be nice to support something a little bit more generic. i.e. an example:

```
var param1 = new Dictionary<string, object>() { { "value", "Foo" } };
var adapter1 = _methodAdapter.Adapt(entry.MethodInfo, param1.GetType());
succeeded = adapter1(entry.Target, param1);

var param2 = new { value = "Foo" };
var adapter2 = _methodAdapter.Adapt(entry.MethodInfo, param2.GetType());
succeeded = adapter2(entry.Target, param2);
```

**Comment by rynowak** [comment]
##### Notice

The infrastructure for publishing notifications has moved to the .Net framework. See the new TelemetrySource and TelemetryListerner APIs in the System.Diagnostics.Tracing.Telemetry package. The infrastructure provided here is for subscribing to events using runtime-generated proxies.

See: https://github.com/dotnet/corefx/pull/2932

----------------------

The reason we didn't do something like is that we're taking advantage of the type-identity of anonymous types to improve performance by generating mappings keyed on the tuple(type, method) which provides a strong identity which is cheap to compute in .Net.

With a dictionary you'd need to do an analysis of the keys and types of the values to determine how to generate the adapter code. This also encourages the publisher to play fast and loose with what data is included, which is the opposite of how we intend it.

**Comment by Eilon** [comment]
Per @rynowak 's comments we are not planning to implement this. You should be able to implement your own adapter to support this.
