### ISSUE TITLE
Problem with walking inheritance chain

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/EventNotification#22]
Currently we have a BeforeAction [event listener](https://github.com/Glimpse/Glimpse.Prototype/blob/dev/src/Glimpse.Agent.AspNet.Mvc/MvcTelemetryListener.cs#L23). In this listener, we have our own `IActionDescriptor` which currently it has a few properties like `DisplayName` and `Id`. This is all as you would expect.

I was looking what other data I could get and started to poke around at underlying data. When doing this, I noticed that the actual type in most cases is `ControllerActionDescriptor`. So as a test, I added `ControllerName` to my `IActionDescriptor`. I was expecting that if this property exists somewhere in the inheritance chain of the underlying type it would bring it across and if it doesn’t (i.e. the object is `FooActionDescriptor` that inherits from `ActionDescriptor` and hence doesn’t have `ControllerName`) it would leave it alone. Currently it doesn’t bring across `ControllerName`, even though its on the underlying type.

**Comment by avanderhoorn** [comment]
I think I know what the problem is. In `TelemetrySourceAdapter` we have the [following](https://github.com/aspnet/EventNotification/blob/dev/src/Microsoft.Framework.TelemetryAdapter/TelemetrySourceAdapter.cs#L98) - the important part being the `GetType()`. Because we a leveraging `GetType()` here, it means that its going to base the rest of the logic off what the compile time definition was and not what the runtime object actually contains. 

With the caching that we are doing, I'm imaging that it makes things harder, but it would be infinity more useful if it could cater for this case, otherwise I have to drop back to type checking to get the required data and at that point I have to take on dependencies on those type.

**Comment by avanderhoorn** [comment]
Thinking about it... I'm guessing that the caching could still work, it would just need to based off the actual types that it sees going by. If the only type it saw was `ControllerActionDescriptor` then it would only have a mapping from it to my type. If it saw `ControllerActionDescriptor` and `FooActionDescriptor`, it would have a cached mapping for both.

**Comment by rynowak** [comment]
We're going to address this by basing each top level item off of the dynamic type of the object. Deeper down in the object graph, you'll have to generate a proxy dynamically by calling into the proxy factory.

**Comment by avanderhoorn** [comment]
Agreed on plan

**Comment by rynowak** [comment]
f90c31c7d47278ab163990120eb1ac2183cf6764
