### ISSUE TITLE
Problem with walking object graph

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/EventNotification#23]
I have the following which aims to mimic the graph of the object being passed in. These types live in my codebase and should be mapped to the data from the origin object being passed in:
```
    public interface IRouteData
    {
        IReadOnlyList<IRouter> Routers { get; }
        IDictionary<string, object> DataTokens { get; }
        IDictionary<string, object> Values { get; }
    }

    public interface IRouter
    {
        string Name { get; }
        string RouteTemplate { get; }
        IDictionary<string, object> Values { get; }
    }
```

Currently, `IRouteData` gets populated and `IRouteData.Routers` even gets populated with multiple items, but the details of those items are all null. Its not mapping the details of the items in the collection.

I suspect that this problem is related to #22 as the publishers type for `IRouteData.Routers` is `List<Microsoft.AspNet.Routing.IRouter>` and `Microsoft.AspNet.Routing.IRouter` doesn't directly implement any of the properties I'm interested in... they are implemented by types that inherit from `Microsoft.AspNet.Routing.IRouter`.

**Comment by rynowak** [comment]
This should be solved by adding `IProxyFactory`. You'll need to iterate the list and generate a proxy of the desired type for each item.

**Comment by rynowak** [comment]
f90c31c7d47278ab163990120eb1ac2183cf6764
