### ISSUE TITLE
React to rename of TelemetrySource to DiagnosticSource

### ISSUE THREAD

**Issue by Eilon** [aspnet/EventNotification#26]
See https://github.com/dotnet/corefx/pull/3552 for details.

The assembly name, namespace, and type names are changing. No behavior changes.

**Comment by Eilon** [comment]
FYI we should be able to act on this very soon as the CoreFx change is merged. Once the NuGet packages are available on the feed we use, we need to make this change. If we wait too long then the types we're using will be marked as `[Obsolete]` and we'll get compiler warnings as errors.

**Comment by Eilon** [comment]
Might be able to give this to New Ryan instead.

**Comment by rynowak** [comment]
```
throw new TooManyRyansException();
```

**Comment by dougbu** [comment]
I see @NewRyan isn't taken. Should reserve it!

**Comment by Eilon** [comment]
Did you mean

```c#
throw new AmbiguousRyanException();
```

?

**Comment by pranavkm** [comment]
Would need to undo this when we get a proper fix: https://github.com/aspnet/Diagnostics/commit/84b91c95fe8acc8eed0a06ba19aae840af5cc664

**Comment by Eilon** [comment]
Yup.

**Comment by JunTaoLuo** [comment]
Merged to dev

**Comment by JunTaoLuo** [comment]
will undo https://github.com/aspnet/Diagnostics/commit/84b91c95fe8acc8eed0a06ba19aae840af5cc664 when https://github.com/aspnet/Hosting/pull/423 is merged
