### ISSUE TITLE
Pascal casing on source object properties

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/EventNotification#27]
When Pascal casing is used for the casing on source object properties, it means that the parameters on the listening method also need to be Pascal casing. Normally this wouldn't be a problem, but when you adjust the casing to be Pascal case on the listening method, the adapter throws an exception.

Here is the test case - https://gist.github.com/avanderhoorn/f0106bca8be1a33acd37 - and here is the exception that is raised: 
 - `ProxyMethodEmitterTest.TargetClassUpperCase` does not contain a definition for 'Name' and no extension method 'Name' accepting a first argument of type `ProxyMethodEmitterTest.TargetClassUpperCase` could be found (are you missing a using directive or an assembly reference?)
 - `<anonymous type: string Name, int Age>` does not contain a definition for 'name' and no extension method 'name' accepting a first argument of type `<anonymous type: string Name, int Age>` could be found (are you missing a using directive or an assembly reference?)
 - `ProxyMethodEmitterTest.TargetClassUpperCase` does not contain a definition for 'Age' and no extension method 'Age' accepting a first argument of type `ProxyMethodEmitterTest.TargetClassUpperCase` could be found (are you missing a using directive or an assembly reference?)
 - `<anonymous type: string Name, int Age>` does not contain a definition for 'age' and no extension method 'age' accepting a first argument of type `<anonymous type: string Name, int Age>` could be found (are you missing a using directive or an assembly reference?)

**Comment by avanderhoorn** [comment]
// @rynowak

**Comment by rynowak** [comment]
Fixed here: c3512b40c633fe16817c5fa5650f3235f7511caf
