### ISSUE TITLE
Provide context in error messages

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/EventNotification#55]
As mentionaed in #53 there isn't enough context in error messages like [this](https://github.com/aspnet/EventNotification/blob/248222ff54848ec7a8967a28eb26dfc1cf8b1fe4/src/Microsoft.Extensions.DiagnosticAdapter/Internal/ProxyTypeEmitter.cs#L118) to make diagnosing issues easy. Let's see about piping through some information like what method was trying to be called.

**Comment by Eilon** [comment]
Is this doable in 1.1.0? Or postpone 'til later?

**Comment by rynowak** [comment]
We could probably wait for feedback on this one if it's hard. I just noticed it while debugging the #53 that error message isn't really helpful unless you know where to look already.

**Comment by Eilon** [comment]
Let's try to fix in 1.1.0, but if we can't, we can move it out.

**Comment by ryanbrandenburg** [comment]
This turned out to be faster than I thought due to using @rynowak's idea about nested exceptions. It's merged in now.
