### ISSUE TITLE
Support new DiagnosticSource.IsEnabled(string, object, object) API

### ISSUE THREAD

**Issue by lmolkova** [aspnet/EventNotification#61]
There were couple of API recently introduced in dotnet/corefx#15984 and dotnet/corefx#15985:
- `DiagnosticSource.IsEnabled(string, object,object)` 
- `DiagnosticListener.Subscribe(IObserver<KeyValuePair<string, object>> observer, Func<string, object, object, bool> isEnabled)`

`DiagnosticListenerExtensions.SubscribeWithAdapter` and `DiagnosticSourceAdapter` constructors should provide an overloads to subscribe with `Func<string, object, object, bool>`

**Comment by Eilon** [comment]
cc @rynowak FYI

**Comment by Eilon** [comment]
@rynowak please chime in if you have any concerns, but this seems like a good idea to me.

**Comment by rynowak** [comment]
Yep. This seems like something we need to do. I don't have any idea yet what the scope of the change is.

**Comment by lmolkova** [comment]
👍
