### ISSUE TITLE
Remove IsEnabled from Write in DiagnosticSourceAdapter

### ISSUE THREAD

**Issue by jbagga** [aspnet/EventNotification#66]
The `Write` method in the `DiagnosticSourceAdapter` calls `InEnabled` which needs to be removed.
https://github.com/aspnet/EventNotification/blob/dev/src/Microsoft.Extensions.DiagnosticAdapter/DiagnosticSourceAdapter.cs#L82-L85

See comment https://github.com/aspnet/EventNotification/pull/65#issuecomment-295539496
See PR: https://github.com/aspnet/EventNotification/pull/65

cc @Eilon @rynowak

**Comment by Eilon** [comment]
Close?

**Comment by jbagga** [comment]
Yeah was just waiting for it to pass on the CI
