### ISSUE TITLE
Port fix for aspnet/Mvc#6292 to patch - KeyNotFoundException in MS.Ext.DiagnosticAdapter.Internal.ProxyTypeEmitter.GetProxyType

### ISSUE THREAD

**Issue by rynowak** [aspnet/EventNotification#76]
We should consider patching aspnet/Mvc#6292

This bug causes errors using app insights or another diagnostic tool and can cause requests to fail with an exception.

**Comment by Eilon** [comment]
This patch is *approved* for 1.1.x. Please follow the patch creation instructions that were sent by email, and submit a PR to the correct branch.

**Comment by rynowak** [comment]
f02f982
