### ISSUE TITLE
Add .NET Standard 2.0 support to the Microsoft.Extensions.DiagnosticAdapter package

### ISSUE THREAD

**Issue by Eilon** [aspnet/EventNotification#83]
And it'll just throw on unsupported platforms, such as UWP.

**Comment by natemcmaster** [comment]
@jbagga you might be able to use the code originally proposed in #70. See https://github.com/aspnet/EventNotification/commit/cc834bfbb398bbac0c14430e5e2243860ef422f1

**Comment by Eilon** [comment]
Ah thanks @natemcmaster , I was looking for the previous discussion on this and couldn't find it. I searched only issues, not PRs!

**Comment by jbagga** [comment]
@natemcmaster Thank you! 
@Eilon The issues Nate mentioned [here](https://github.com/aspnet/EventNotification/pull/70#issue-234356616) still exist (`PlatformNotSupportedException` for a public API and some .Internal types). Do we still want to go ahead?
